language: android

env:
  global:
    - COMPILE_SDK_VERSION=27 
    - BUILD_TOOLS_VERSION=27.0.3



android:
  components:
    - tools # Update android-sdk (also called android-sdk-tools)
    - platform-tools
    - tools # Write the second time to update to thes newest as described in the document
    - build-tools-${BUILD_TOOLS_VERSION} # For building
    - android-${COMPILE_SDK_VERSION} # For building
    - extra-android-m2repository # Support library


before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew
  - rm -fr $HOME/android-ndk-r16b
  - curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
  - unzip -oq android-ndk-r16b-linux-x86_64.zip
  - rm android-ndk-r16b-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r16b

install:
  - sdkmanager --list || true # Debug / Observation
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" #&> /dev/null
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2" #&> /dev/null
  - avdmanager --list || true  # Debug / Observation