language: android
sudo: true

env:
  global:
    - COMPILE_SDK_VERSION=27 
    - BUILD_TOOLS_VERSION=27.0.2

android:
  components:
    - tools # Update android-sdk (also called android-sdk-tools)
    - platform-tools
    - tools # Write the second time to update to thes newest as described in the document
    - build-tools-${BUILD_TOOLS_VERSION} # For building
    - android-${COMPILE_SDK_VERSION} # For building
    - extra-android-m2repository # Support library

before_install:
  - chmod +x gradlew

install:
  - sdkmanager --list || true # Debug / Observation
  - echo y | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" #&> /dev/null
  - echo y | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2" #&> /dev/null
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - echo y | sdkmanager 'lldb;3.0'
  - echo y | sdkmanager "platforms;android-27"
  - avdmanager --list || true  # Debug / Observation

before_deploy:
  - "cp app/build/outputs/apk/debug/app-debug.apk"
  - "cp app/build/outputs/mapping/debug/mapping.txt"
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy-telegram.sh
    on:
      branch: alpha
